### ISSUE TITLE
Missing command line code

### ISSUE THREAD

**Issue by kaseyzapatka** [Jonahznl/Computational-Social-Science-Projects.#1]
Hi Jonah, 

Not sure if you are finished yet but just wanted to make sure you submit the command line code you used to create the repo in this repo as well, since that was part of the assignment. 

Kasey

**Comment by Jonahznl** [comment]
Thank you for the reminder Kasey! I just pushed it to the repo.

**Comment by kaseyzapatka** [comment]
Great. In general, the commands you use seem correct, but they are missing the object they create. For example, `mkdir` make a directory, but which one? If you could update that part of it before the deadline, that'd be great.

**Comment by Jonahznl** [comment]
I just updated the commands.txt in this repo and the jonah_commands.txt in the group project repo.
